#!/bin/bash

SELF="$(realpath "$0")"
REAL_SQLCMD=""

for cmd in $(which -a sqlcmd); do
    if [[ "$(realpath "$cmd")" != "$SELF" ]]; then
        REAL_SQLCMD="$cmd"
        break
    fi
done

if [[ -z "$REAL_SQLCMD" ]]; then
    echo "Error: Could not find real sqlcmd binary" >&2
    exit 1
fi

exec "$REAL_SQLCMD" "$@" -k
